const Products = [
  {
    id: 1,
    item: "Customized Toddler Color Books",
    img: "kids.jpg",
    price: "Ksh.950",
    collection: "Kids",
    dimensions: "15cm x 15cm",
    
  },
  {
    id: 2,
    item: "Customized Disney Color Books",
    img: "disney.jpg",
    price: "Ksh.950",
    collection: "Kids",
    dimensions: "15cm x 15cm",
  },
  {
    id: 3,
    item: "Pocket Planner",
    img: "pocketblack.jpg",
    price: "Ksh.650",
    collection: "Nkatha_K",
    dimensions: "9cm x 13cm",
    color: "Black, Coffee Brown",
  },
  {
    id: 4,
    item: "Desk Planner",
    img: "deskplanner.jpg",
    price: "Ksh.2700",
    collection: "Nkatha_K",
    dimensions: "24cm x 28cm",
    color: "",
  },
  {
    id: 5,
    item: "Customized Planners",
    img: "custom.jpg",
    price: "Ksh.",
    collection: "Nkatha_K",
  },
  {
    id: 6,
    item: "2023 Planner",
    img: "2023.jpg",
    price: "Ksh.1450",
    collection: "Planners",
  },
  {
    id: 7,
    item: "Daily Planner",
    img: "daily.jpg",
    price: "Ksh.1,450",
    collection: "Planners",
  },
  {
    id: 8,
    item: "Art Color Pens",
    img: "pens.jpg",
    price: "Ksh.900",
    collection: "Pens",
  },
  {
    id: 9,
    item: "Photo Journal",
    img: "bigphoto.jpg",
    price: "Ksh.2050",
    collection: "Photo Journal",
    dimensions: "24cm x 22cm",
  },
  {
    id: 10,
    item: "Mini Photo Journal",
    img: "miniphoto.jpg",
    price: "Ksh.1050",
    collection: "female",
    dimensions: "11cm x 15cm",
  },
  {
    id: 11,
    item: "Black Dot Grid Notebook",
    img: "blackgrid.jpg",
    price: "Ksh.2800",
    collection: "Notebook",
  },
  {
    id: 12,
    item: "Mental Health Journal",
    img: "mentalh.jpg",
    price: "Ksh.1600",
    collection: "Journal",
  },
];

export default Products;
